//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKentService.Services.BulutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BulutService.OutsourceIntegration7Soap")]
    public interface OutsourceIntegration7Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TKentService.Services.BulutService.ListResultOfTransaction GetTransactions(string Key, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<TKentService.Services.BulutService.ListResultOfTransaction> GetTransactionsAsync(string Key, System.DateTime Date);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResultOfTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string messageField;
        
        private Transaction[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Transaction[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private System.DateTime dateField;
        
        private long idField;
        
        private string commentField;
        
        private string memberAccountCodeField;
        
        private string memberAccountNameField;
        
        private string renterTitleField;
        
        private string renterEmailField;
        
        private string renterPIDOrTaxIDField;
        
        private string contraAccountField;
        
        private decimal amountField;
        
        private byte taxRateField;
        
        private System.DateTime recordDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MemberAccountCode {
            get {
                return this.memberAccountCodeField;
            }
            set {
                this.memberAccountCodeField = value;
                this.RaisePropertyChanged("MemberAccountCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MemberAccountName {
            get {
                return this.memberAccountNameField;
            }
            set {
                this.memberAccountNameField = value;
                this.RaisePropertyChanged("MemberAccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RenterTitle {
            get {
                return this.renterTitleField;
            }
            set {
                this.renterTitleField = value;
                this.RaisePropertyChanged("RenterTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RenterEmail {
            get {
                return this.renterEmailField;
            }
            set {
                this.renterEmailField = value;
                this.RaisePropertyChanged("RenterEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RenterPIDOrTaxID {
            get {
                return this.renterPIDOrTaxIDField;
            }
            set {
                this.renterPIDOrTaxIDField = value;
                this.RaisePropertyChanged("RenterPIDOrTaxID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ContraAccount {
            get {
                return this.contraAccountField;
            }
            set {
                this.contraAccountField = value;
                this.RaisePropertyChanged("ContraAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public byte TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
                this.RaisePropertyChanged("TaxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
                this.RaisePropertyChanged("RecordDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OutsourceIntegration7SoapChannel : TKentService.Services.BulutService.OutsourceIntegration7Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutsourceIntegration7SoapClient : System.ServiceModel.ClientBase<TKentService.Services.BulutService.OutsourceIntegration7Soap>, TKentService.Services.BulutService.OutsourceIntegration7Soap {
        
        public OutsourceIntegration7SoapClient() {
        }
        
        public OutsourceIntegration7SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutsourceIntegration7SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutsourceIntegration7SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutsourceIntegration7SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TKentService.Services.BulutService.ListResultOfTransaction GetTransactions(string Key, System.DateTime Date) {
            return base.Channel.GetTransactions(Key, Date);
        }
        
        public System.Threading.Tasks.Task<TKentService.Services.BulutService.ListResultOfTransaction> GetTransactionsAsync(string Key, System.DateTime Date) {
            return base.Channel.GetTransactionsAsync(Key, Date);
        }
    }
}
